CREATE TABLE PERSON(
  PERSON_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(32) NOT NULL,
  LAST_NAME VARCHAR(32) NOT NULL,
  EMAIL_ADDRESS VARCHAR(128) NOT NULL
);
CREATE TABLE TASK(
  TASK_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  PERSON_ID INTEGER NOT NULL,
  TASK VARCHAR(2048) NOT NULL,
  COMPLETED BOOLEAN,
  FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
);
